### ISSUE TITLE
Heavy Images

### ISSUE THREAD

**Issue by konchady** [deekshithpk/HarFade#9]
I just downloaded the latest update and realized that the trim files are heavy (each one is approx 7 MB). The compressed version of the folder is 8.2 MB but the overall file after decompression is 63 MB. No need to worry, just thought of mentioning it. 

Also while putting it up on arxiv, if and when we plan to, we need to modify these image files since there is an upload memory limit for documents.

**Comment by deekshithpk** [comment]
Sure
